spring.application.name=fintech-reconciliation-batch

# ==========================================
# DATABASE SQL (H2)
# ==========================================
spring.datasource.url=jdbc:h2:mem:fintech_db
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# DATABASE NOSQL (MONGODB ATLAS)
# ==========================================
spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.sfkzdiu.mongodb.net/${MONGO_DATABASE}?retryWrites=true&w=majority&appName=Cluster0

# ==========================================
# JPA/Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# 3. SPRING BATCH
# ==========================================
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# ==========================================
# 4. ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=health,metrics